// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929021917_SeedVillasToDb")]
    partial class SeedVillasToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7e2704c-8505-4e4c-aa2f-7ea1e9b9b823"),
                            CreatedAt = new DateTime(2025, 9, 29, 9, 19, 17, 166, DateTimeKind.Local).AddTicks(9973),
                            Description = "A luxurious villa with stunning sea views.",
                            ImageUrl = "https://example.com/images/royal-villa.jpg",
                            IsDeleted = false,
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 500.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = new Guid("dbc0c36d-5211-4012-a070-33ce40357c4c"),
                            CreatedAt = new DateTime(2025, 9, 29, 9, 19, 17, 166, DateTimeKind.Local).AddTicks(9978),
                            Description = "A premium villa with a private pool and garden.",
                            ImageUrl = "https://example.com/images/premium-pool-villa.jpg",
                            IsDeleted = false,
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 500
                        },
                        new
                        {
                            Id = new Guid("22f60f72-ac50-471a-bd14-3ceed231858c"),
                            CreatedAt = new DateTime(2025, 9, 29, 9, 19, 17, 166, DateTimeKind.Local).AddTicks(9981),
                            Description = "A mornal villa with a no pool and a small garden.",
                            ImageUrl = "https://example.com/images/normal-garden-villa.jpg",
                            IsDeleted = false,
                            Name = "Normal Pool Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 250
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
